sudo: required
services:
    - docker

before_install:
    - docker build -t hicofish/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true hicofish/react-test npm test -- --coverage

after_success:
    - docker build -t hicofish/multi-client ./client
    - docker build -t hicofish/multi-nginx ./nginx
    - docker build -t hicofish/multi-server ./server
    - docker build -t hicofish/multi-worker ./worker

    # Log in to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take images and push them to docker hub
    - docker push hicofish/multi-client
    - docker push hicofish/multi-nginx
    - docker push hicofish/multi-server
    - docker push hicofish/multi-worker